Import('env')

sources = Split("""
	lapi.c 
	lcode.c 
	ldebug.c 
	ldo.c 
	ldump.c 
	lfunc.c 
	lgc.c 
	llex.c 
	lmem.c 
	lobject.c 
	lopcodes.c 
	lparser.c 
	lstate.c 
	lstring.c 
	ltable.c 
	ltm.c 
	lundump.c 
	lvm.c 
	lzio.c 
	lauxlib.c 
	lbaselib.c 
	ldblib.c 
	liolib.c 
	lmathlib.c 
	loslib.c 
	lstrlib.c 
	ltablib.c 
	loadlib.c 
	linit.c
	bit.c
""")

lua = env.Library('lua' + env['DGREED_POSTFIX'], sources)
env.Install('#'+env['DGREED_BIN_DIR'], lua)

Return('lua')

