Import('env')

NAME='gyvis'
ASSETS_DIR = NAME + '_assets'

sources = Glob('*.cpp', strings=True)

if str(Platform()) == 'win32':
	sources += [env.RES('resource.rc')]

app = env.Program(NAME + env['DGREED_POSTFIX'], sources, \
	LIBS=env['DGREED_EGO_LIB'] + env['DGREED_LIBS'])
env.Install('#'+env['DGREED_BIN_DIR'], app)

# Copy assets only in debug build
if env['DGREED_POSTFIX'] == 'd':
	dest_dir = '#' + env['DGREED_BIN_DIR'] + '/' + ASSETS_DIR
	for asset in Glob(ASSETS_DIR + '/*', strings=True):
		if asset.endswith('.fnt'):
			env.Command('#' + env['DGREED_BIN_DIR']+'/'+ asset.replace('.fnt', '.bft'), 
				asset, env['DGREED_FONT_TOOL'])
		if asset.endswith('.png') or asset.endswith('.ogg') or \
			asset.endswith('.wav'):		
			env.Install(dest_dir, asset)

