Import('env')

NAME='tamsa'

sources = Glob('*.c', strings=True)
app = env.Program(NAME + env['DGREED_POSTFIX'], sources, LIBS=env['DGREED_LIBS'])
env.Install('#'+env['DGREED_BIN_DIR'], app)

