dialog_text = {
	{"Justis:", "Hello girl, how are you? WHERE ARE YOU FASDASDASDASDASDASDASDAS \
	ASDADASDASDSADASDADA DA AASDSASDASDAD ASDASDASDASD ASDASDASDADSADA \
	ASDASDASDASD   asdasROM WHERE ARE YOU FROM WHERE ARE \
	YOU FTOM where are YOU GTOM WHERE ARE YOU FTOM?ARE MYTE ASDASD ERERE DSDSDS \
	VEVEVE BRBRbr bntntnt asdad?" },
	{ "Mergele:", "Hi there!"}
}

