Import('env')

malka = SConscript('malka/SConscript', exports='env')

sources = Glob('*.c', strings=True)

if str(Platform()) == 'darwin':
	sources += ['NSFileManager+DirectoryLocations.m', 'SDLMain.m']
	env.Append(LINKFLAGS=' -all_load')

dgreed = env.Library('dgreed' + env['DGREED_POSTFIX'], sources)
env.Install('#'+env['DGREED_BIN_DIR'], dgreed)

ego_sources = Glob('*.cpp', strings=True)
ego = env.Library('ego' + env['DGREED_POSTFIX'], ego_sources)
env.Install('#'+env['DGREED_BIN_DIR'], ego)

