Import('env')

NAME='spurga'
ASSETS_DIR = NAME + '_assets'
SCRIPTS_DIR = NAME + '_scripts'

sources = Glob('*.c', strings=True)

app = env.Program(NAME + env['DGREED_POSTFIX'], sources, LIBS=env['MALKA_LIBS']\
	+env['DGREED_LIBS'])
env.Install('#'+env['DGREED_BIN_DIR'], app)

# Copy assets and scripts only in debug build
if env['DGREED_POSTFIX'] == 'd':
	dest_dir = '#' + env['DGREED_BIN_DIR'] + '/' + ASSETS_DIR
	for asset in Glob(ASSETS_DIR + '/*', strings=True):
		if asset.endswith('.wav') or \
			asset.endswith('.ogg') or asset.endswith('.mml') or \
			asset.endswith('.bft'):
			env.Install(dest_dir, asset)
		if asset.endswith('.png') and asset.find('lvl_') == -1:
			env.Install(dest_dir, asset)
	
	dest_dir = '#' + env['DGREED_BIN_DIR'] + '/' + SCRIPTS_DIR
	for script in Glob(SCRIPTS_DIR + '/*.lua', strings=True):
		if env['DGREED_LUA']:
			env.Command('#' + env['DGREED_BIN_DIR']+'/' + script.replace('.lua', '.lc'),
			script, env['DGREED_LUA'])
		else:
			env.Install(dest_dir, script)

