Import('env')

lua = SConscript('lua/SConscript', exports='env')

NAME='malka'
postfix = env['DGREED_POSTFIX']

sources = Split("""
	malka.c
	ml_utils.c
	ml_system.c
	ml_mml.c
	ml_states.c
""")

malka = env.Library(NAME + postfix, sources)
env.Install('#'+env['DGREED_BIN_DIR'], malka)
env.Depends(malka, lua)

