Import('env')

NAME='tor'
ASSETS_DIR = NAME + '_assets'

sources = Glob('*.c', strings=True)
app = env.Program(NAME + env['DGREED_POSTFIX'], sources, LIBS=env['DGREED_LIBS'])
env.Install('#'+env['DGREED_BIN_DIR'], app)

# Copy assets only in debug build
if env['DGREED_POSTFIX'] == 'd':
	dest_dir = '#' + env['DGREED_BIN_DIR'] + '/' + ASSETS_DIR
	for asset in Glob(ASSETS_DIR + '/*', strings=True):
		if asset.endswith('.fnt'):
			env.Command('#' + env['DGREED_BIN_DIR']+'/'+ asset.replace('.fnt', '.bft'), 
				asset, env['DGREED_FONT_TOOL'])
		else:		
			env.Install(dest_dir, asset)

